### ISSUE TITLE
Example curl command returns 404 

### ISSUE THREAD

**Issue by ghost** [bodywork-ml/bodywork-scikit-fastapi-project#1]
Hi! Thanks for putting this together! Noticed the curl command in the [example](https://github.com/bodywork-ml/bodywork-scikit-fastapi-project#:~:text=some%20data%20using-,curl,-%2C) returns a 404.
Can be replaced with this to return the desired response!

'http://localhost:8000/api/v1/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "X": 42
}'

Thanks!

**Comment by AlexIoannides** [comment]
Which version of Bodywork are you using to deploy it?

You can get this by running `bodywork version`.

**Comment by ghost** [comment]
`bodywork --version`
returns 2.0.2
